// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBlcC831nYpwzswtHIO1WNSQxit-OP04I',
    appId: '1:1037822012115:web:ff8b0efe1763b917bc8226',
    messagingSenderId: '1037822012115',
    projectId: 'my-clothing-app-rev9',
    authDomain: 'my-clothing-app-rev9.firebaseapp.com',
    storageBucket: 'my-clothing-app-rev9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_SlU_9sYEtX1LMveM5GEpSK8hGdafpNk',
    appId: '1:1037822012115:android:0a59466e2bc52d6dbc8226',
    messagingSenderId: '1037822012115',
    projectId: 'my-clothing-app-rev9',
    storageBucket: 'my-clothing-app-rev9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLqJ3r5_EdZ7sXxsL3M2X-VKwhA07egjI',
    appId: '1:1037822012115:ios:2e34e88e2ca6edf4bc8226',
    messagingSenderId: '1037822012115',
    projectId: 'my-clothing-app-rev9',
    storageBucket: 'my-clothing-app-rev9.firebasestorage.app',
    iosBundleId: 'com.example.clothingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLqJ3r5_EdZ7sXxsL3M2X-VKwhA07egjI',
    appId: '1:1037822012115:ios:2e34e88e2ca6edf4bc8226',
    messagingSenderId: '1037822012115',
    projectId: 'my-clothing-app-rev9',
    storageBucket: 'my-clothing-app-rev9.firebasestorage.app',
    iosBundleId: 'com.example.clothingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBlcC831nYpwzswtHIO1WNSQxit-OP04I',
    appId: '1:1037822012115:web:2bf3298deada6fdabc8226',
    messagingSenderId: '1037822012115',
    projectId: 'my-clothing-app-rev9',
    authDomain: 'my-clothing-app-rev9.firebaseapp.com',
    storageBucket: 'my-clothing-app-rev9.firebasestorage.app',
  );
}
